config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users

  root to: "projects#index"
  resources :projects do 
    resources :tickets
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true 

  has_many :tickets,dependent: :destroy
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project

  validates :title,:description,presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project,only: [:edit,
                                     :update,
                                     :show,
                                     :destroy]
  def index
    @projects = Project.order :title
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new params[:project]

    if @project.save
      redirect_to @project, notice: "Project has been created"
    else
      flash[:alert]="Project has not been created"
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @project.update_attributes! params[:project]
    redirect_to @project,notice: "Project has been updated"
  rescue
    flash[:alert]="Project has not been updated"
    render "edit"
  end

  def destroy
    @project.destroy
    redirect_to root_url,notice: "Project has been deleted."
  end

private
  def find_project  
    @project = Project.find params[:id]
  rescue
    redirect_to root_url, alert: "The project you looking for hasnot been found"
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_project
  before_filter :find_ticket , only: [:show, 
                                      :edit,
                                      :update,
                                      :destroy]

  def show
  end

  def new
    @ticket=@project.tickets.new
  end

  def create
    @ticket=@project.tickets.new params[:ticket]


    respond_to do |format|
      if @ticket.save
        format.html {redirect_to [@project,@ticket],notice: "Ticket has been created."}
      else
        format.html {
          flash[:alert]="Ticket has not been created"
          render "new"
        }
      end
    end
  end

  def edit
  end

  def update
    @ticket.update_attributes! params[:ticket]
    redirect_to [@project,@ticket],notice: "Ticket has been updated."

  rescue
    flash[:alert]="Ticket has not been updated."
    render "edit"
  end

  def destroy
    @ticket.destroy
    redirect_to @project,notice: "Ticket has been deleted."
  end

private
  def find_project
    @project = Project.find params[:project_id]
  rescue
    redirect_to root_url, alert: "The project you looking for has not been found" 
  end

  def find_ticket
    @ticket= @project.tickets.find params[:id] 
  rescue
    redirect_to root_url, alert: "The project you looking for has not been found" 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title Ticketee - The Project Manager

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body{class: controller.controller_name}

    - if notice
      %p#notice= notice
    - if alert
      %p#alert= alert

    - if user_signed_in?
      = link_to "Sign out",destroy_user_session_path
      %br
      %p= "Signed in as #{current_user.email}"
    - else
      = link_to "Sign in",new_user_session_path
      %br
      = link_to "Sign up",new_user_registration_path

    = yield

app/views/projects/_form.html.haml
%div.form
  - if @project.errors.any?
    %fieldset
      %legend Errors
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend Project Information
    = form_for @project do |f|
      = f.label :title
      = f.text_field :title

      = f.submit

app/views/projects/edit.html.haml
%h1 Edit Project
= render "form"
=link_to "Home", root_url

app/views/projects/index.html.haml
%h1 Project list
- @projects.each do |project|
  =link_to project.title, project
=link_to "New Project", new_project_path

app/views/projects/new.html.haml
%h1 New Project
= render "form"
=link_to "Home", root_url

app/views/projects/show.html.haml
%h1= @project.title

- if @project.tickets.any?
  %ul
    - @project.tickets.each do |ticket|
      %li= link_to ticket.title,[@project,ticket]

= link_to "Edit", edit_project_path(@project)
%br
= link_to "Delete Project", project_path(@project), method: :delete
%br
= link_to "Home",root_url
%br
= link_to "New Ticket",new_project_ticket_path(@project)

app/views/tickets/_form.html.haml
%div.form
  - if @ticket.errors.any?
    %fieldset
      %legend Errors
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend Project Information
    = form_for [@project,@ticket] do |f|
      = f.label :title
      = f.text_field :title

      = f.label :description
      = f.text_area :description

      = f.submit

app/views/tickets/edit.html.haml
%h1 Edit Ticket

= render "form"

app/views/tickets/new.html.haml
%h1 New Ticket

= render "form"

= link_to "Back to Project",@project
%br
= link_to "Back to home page",root_url

app/views/tickets/show.html.haml
%h1= @ticket.title

%p#description= @ticket.description

= link_to "Edit Ticket",edit_project_ticket_path(@project,@ticket)
%br
= link_to "Delete Ticket",project_ticket_path(@project,@ticket),method: :delete